# Generated by Django 5.0.3 on 2024-09-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Additional_information',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
