# Generated by Django 5.0.3 on 2024-09-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_ref_code_payment_amount_payment_pidx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pidx',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
