# Generated by Django 5.0.3 on 2024-09-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_payment_pidx_alter_payment_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='apartment_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
