# Generated by Django 5.0.3 on 2024-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_apartment_address_address_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.IntegerField(default=9878787878),
            preserve_default=False,
        ),
    ]
