# Generated by Django 5.0.3 on 2024-09-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='ref_code',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
