# Generated by Django 5.0.3 on 2025-04-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signature',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
