# Generated by Django 5.0.3 on 2025-04-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('primary', 'New'), ('secondary', 'Featured'), ('danger', 'Limited'), ('warning', 'Hot'), ('info', 'Exclusive')], default='primary', max_length=30),
        ),
    ]
